#!/usr/bin/sh
pactl set-sink-volume @DEFAULT_SINK@ +2%
VOLUME=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
notify-send -a "🔊" "$VOLUME"

